#!/usr/bin/env python3
"""Generate a project-local, multi-environment DBHub MCP configuration."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shlex
import shutil
import stat
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


SOURCE_ID_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]*$")
SOURCE_TYPE_PATTERN = re.compile(r"^[A-Za-z][A-Za-z0-9_-]*$")
ALLOWED_SOURCE_TYPES = {"mariadb", "mysql", "postgres", "sqlite", "sqlserver"}
KEYCHAIN_SERVICE_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")
MCP_HEADER = "[mcp_servers.dbhub]"
MYSQL_TIMEZONE_PATTERN = re.compile(r"^(?:local|Z|[+-]\d\d:\d\d)$")
DEFAULT_MYSQL_TIMEZONE = "+08:00"
DBHUB_VERSION_PATTERN = re.compile(r"^\d+\.\d+\.\d+$")
QUALIFIED_RUNNER_PATH = Path(__file__).resolve().parent / "run_qualified_dbhub.py"
QUALIFICATION_STATE_DIR = Path.home() / ".codex/state/dbhub-setup"
PYTHON_EXECUTABLE = Path(shutil.which("python3") or sys.executable).resolve()


@dataclass(frozen=True)
class Source:
    source_id: str
    db_type: str
    host: str
    port: int
    database: str
    user: str
    label: str
    credential_id: str

    @property
    def password_env(self) -> str:
        normalized = re.sub(r"[^A-Za-z0-9]", "_", self.source_id).upper()
        return f"DBHUB_{normalized}_PASSWORD"


def parse_source(raw: str) -> Source:
    parts = raw.split("|")
    if len(parts) not in (6, 7, 8):
        raise argparse.ArgumentTypeError(
            "--source must be "
            "id|type|host|port|database|user[|DISPLAY LABEL[|KEYCHAIN ACCOUNT]]"
        )

    source_id, db_type, host, port_text, database, user = parts[:6]
    label = parts[6] if len(parts) == 7 else source_id.upper()
    if len(parts) == 8:
        label = parts[6]
        credential_id = parts[7]
    else:
        credential_id = source_id

    if not SOURCE_ID_PATTERN.fullmatch(source_id):
        raise argparse.ArgumentTypeError(
            f"invalid source id {source_id!r}; use letters, digits, '_' or '-'"
        )
    if not SOURCE_TYPE_PATTERN.fullmatch(db_type):
        raise argparse.ArgumentTypeError(f"invalid database type {db_type!r}")
    if db_type.lower() not in ALLOWED_SOURCE_TYPES:
        raise argparse.ArgumentTypeError(
            f"unsupported qualified database type {db_type!r}"
        )
    if any(not value for value in (host, database, user, label)):
        raise argparse.ArgumentTypeError(
            "host, database, user, and display label must be non-empty"
        )
    if "|" in label or "\n" in label or "\r" in label:
        raise argparse.ArgumentTypeError("display label cannot contain '|', CR, or LF")
    if not SOURCE_ID_PATTERN.fullmatch(credential_id):
        raise argparse.ArgumentTypeError(
            f"invalid keychain account {credential_id!r}; "
            "use letters, digits, '_' or '-'"
        )

    try:
        port = int(port_text)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(f"invalid port {port_text!r}") from exc
    if not 1 <= port <= 65535:
        raise argparse.ArgumentTypeError("port must be between 1 and 65535")

    return Source(
        source_id=source_id.lower(),
        db_type=db_type.lower(),
        host=host,
        port=port,
        database=database,
        user=user,
        label=label,
        credential_id=credential_id.lower(),
    )


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_dbhub_config(
    sources: Iterable[Source],
    *,
    max_rows: int,
    connection_timeout: int,
    query_timeout: int,
    mysql_timezone: str,
) -> str:
    blocks: list[str] = [
        "# Generated by the dbhub-setup skill. Passwords must remain environment variables."
    ]
    for source in sources:
        blocks.extend(
            [
                "",
                "[[sources]]",
                f"id = {toml_string(source.source_id)}",
                (
                    "description = "
                    f"{toml_string(f'{source.label} database (password supplied per DBHub process)')}"
                ),
                f"type = {toml_string(source.db_type)}",
                f"host = {toml_string(source.host)}",
                f"port = {source.port}",
                f"database = {toml_string(source.database)}",
                f"user = {toml_string(source.user)}",
                f'password = "${{{source.password_env}}}"',
                f"connection_timeout = {connection_timeout}",
                f"query_timeout = {query_timeout}",
                *(
                    [f"timezone = {toml_string(mysql_timezone)}"]
                    if source.db_type in ("mysql", "mariadb")
                    else []
                ),
                "lazy = true",
                "",
                "[[tools]]",
                'name = "execute_sql"',
                f"source = {toml_string(source.source_id)}",
                "readonly = true",
                f"max_rows = {max_rows}",
                "",
                "[[tools]]",
                'name = "search_objects"',
                f"source = {toml_string(source.source_id)}",
            ]
        )
    return "\n".join(blocks) + "\n"


def render_launcher(
    sources: Iterable[Source],
    *,
    dbhub_version: str,
    keychain_service: str,
    config_sha256: str,
) -> str:
    source_list = list(sources)
    load_blocks: list[str] = []
    for credential_id, credential_sources in credential_groups(source_list):
        arguments = [credential_id, *(source.password_env for source in credential_sources)]
        continuation = " \\\n  ".join(shlex.quote(argument) for argument in arguments)
        load_blocks.append(f"load_keychain_password \\\n  {continuation}")
    keychain_loads = "\n\n".join(
        "\n".join(f"  {line}" for line in block.splitlines())
        for block in load_blocks
    )
    return f"""#!/bin/zsh
# dbhub-setup-launcher-schema: 2

set -eu

readonly SCRIPT_DIR="${{0:A:h}}"
readonly CONFIG_PATH="${{SCRIPT_DIR}}/dbhub.toml"
readonly KEYCHAIN_SERVICE={shlex.quote(keychain_service)}
readonly QUALIFIED_RUNNER={shlex.quote(str(QUALIFIED_RUNNER_PATH))}
readonly QUALIFICATION_STATE_DIR={shlex.quote(str(QUALIFICATION_STATE_DIR))}
readonly PYTHON_EXECUTABLE={shlex.quote(str(PYTHON_EXECUTABLE))}

if [[ ! -r "${{CONFIG_PATH}}" ]]; then
  print -u2 -- "DBHub config is not readable: ${{CONFIG_PATH}}"
  exit 1
fi

load_keychain_password() {{
  local keychain_account="$1"
  local password_env_name
  local keychain_password
  local password_missing=0
  shift

  for password_env_name in "$@"; do
    if [[ -z "${{(P)password_env_name:-}}" ]]; then
      password_missing=1
      break
    fi
  done

  if (( password_missing == 0 )); then
    return 0
  fi

  if [[ "$(/usr/bin/uname -s)" != "Darwin" ]]; then
    print -u2 -- "DBHub password '${{keychain_account}}' is missing and macOS Keychain is unavailable."
    return 1
  fi

  keychain_password="$(
    /usr/bin/security find-generic-password \\
      -a "${{keychain_account}}" \\
      -s "${{KEYCHAIN_SERVICE}}" \\
      -w 2>/dev/null
  )" || {{
    print -u2 -- "DBHub could not read account '${{keychain_account}}' from macOS Keychain."
    print -u2 -- "Create it in a terminal with:"
    print -u2 -- "  /usr/bin/security add-generic-password -U -a '${{keychain_account}}' -s '${{KEYCHAIN_SERVICE}}' -l 'DBHub ${{keychain_account}}' -w"
    return 1
  }}

  if [[ -z "${{keychain_password}}" ]]; then
    print -u2 -- "DBHub found an empty password for account '${{keychain_account}}' in macOS Keychain."
    return 1
  fi

  for password_env_name in "$@"; do
    if [[ -z "${{(P)password_env_name:-}}" ]]; then
      typeset -gx "${{password_env_name}}=${{keychain_password}}"
    fi
  done

  unset keychain_password password_env_name
}}

load_all_passwords() {{
{keychain_loads}
}}

if [[ "${{DBHUB_LAUNCHER_CHECK_ONLY:-0}}" == "1" ]]; then
  load_all_passwords
  print -- "DBHub launcher check passed: required passwords were loaded without printing them."
  exit 0
fi

if [[ ! -r "${{QUALIFIED_RUNNER}}" ]]; then
  print -u2 -- "DBHub qualified runtime runner is not readable: ${{QUALIFIED_RUNNER}}"
  exit 1
fi

# DBHUB_QUALIFIED_PREFLIGHT_BEGIN
"${{PYTHON_EXECUTABLE}}" "${{QUALIFIED_RUNNER}}" \\
  --version {shlex.quote(dbhub_version)} \\
  --state-dir "${{QUALIFICATION_STATE_DIR}}" \\
  --expected-config-sha256 {shlex.quote(config_sha256)} \\
  --validate-config "${{CONFIG_PATH}}"
# DBHUB_QUALIFIED_PREFLIGHT_END

load_all_passwords

exec "${{PYTHON_EXECUTABLE}}" "${{QUALIFIED_RUNNER}}" \\
  --version {shlex.quote(dbhub_version)} \\
  --state-dir "${{QUALIFICATION_STATE_DIR}}" \\
  --expected-config-sha256 {shlex.quote(config_sha256)} \\
  -- \\
  --transport stdio \\
  --config="${{CONFIG_PATH}}"
"""


def render_mcp_table(project_root: Path) -> str:
    launcher = project_root / ".codex" / "dbhub" / "start-dbhub.zsh"
    return "\n".join(
        [
            MCP_HEADER,
            f"command = {toml_string(str(launcher))}",
            "args = []",
            f"cwd = {toml_string(str(project_root))}",
            "enabled = true",
        ]
    )


def upsert_mcp_table(existing: str, table: str, *, force: bool) -> str:
    lines = existing.splitlines()
    start = next(
        (index for index, line in enumerate(lines) if line.strip() == MCP_HEADER),
        None,
    )
    if start is None:
        prefix = existing.rstrip()
        return f"{prefix}\n\n{table}\n" if prefix else f"{table}\n"
    if not force:
        raise RuntimeError(
            f"{MCP_HEADER} already exists in .codex/config.toml; inspect it and rerun with --force"
        )

    end = len(lines)
    for index in range(start + 1, len(lines)):
        stripped = lines[index].strip()
        if not stripped.startswith("["):
            continue
        if stripped.startswith("[mcp_servers.dbhub.") or stripped.startswith(
            "[[mcp_servers.dbhub."
        ):
            continue
        end = index
        break
    replacement = lines[:start] + table.splitlines() + lines[end:]
    return "\n".join(replacement).rstrip() + "\n"


def atomic_write(path: Path, content: str, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    file_descriptor, temp_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=str(path.parent), text=True
    )
    temp_path = Path(temp_name)
    try:
        with os.fdopen(file_descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        os.chmod(temp_path, mode)
        os.replace(temp_path, path)
    finally:
        if temp_path.exists():
            temp_path.unlink()


def git_exclude_path(project_root: Path) -> Path | None:
    result = subprocess.run(
        ["git", "rev-parse", "--git-path", "info/exclude"],
        cwd=project_root,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        return None
    path = Path(result.stdout.strip())
    return path if path.is_absolute() else project_root / path


def add_git_exclude(project_root: Path) -> str | None:
    exclude_path = git_exclude_path(project_root)
    if exclude_path is None:
        return None

    existing = exclude_path.read_text(encoding="utf-8") if exclude_path.exists() else ""
    if any(line.strip() == ".codex/" for line in existing.splitlines()):
        return str(exclude_path)

    content = existing
    if content and not content.endswith("\n"):
        content += "\n"
    content += "\n### Local Codex DBHub configuration ###\n.codex/\n"
    current_mode = (
        stat.S_IMODE(exclude_path.stat().st_mode) if exclude_path.exists() else 0o644
    )
    atomic_write(exclude_path, content, current_mode)
    return str(exclude_path)


def ensure_unique_sources(sources: list[Source]) -> None:
    source_ids: set[str] = set()
    password_envs: set[str] = set()
    credential_bindings: dict[str, tuple[str, str, int, str]] = {}
    for source in sources:
        if source.source_id in source_ids:
            raise RuntimeError(f"duplicate source id: {source.source_id}")
        if source.password_env in password_envs:
            raise RuntimeError(
                f"source ids produce duplicate password variable: {source.password_env}"
            )
        source_ids.add(source.source_id)
        password_envs.add(source.password_env)
        binding = (source.db_type, source.host, source.port, source.user)
        previous_binding = credential_bindings.setdefault(
            source.credential_id, binding
        )
        if previous_binding != binding:
            raise RuntimeError(
                f"keychain account {source.credential_id!r} is shared by sources "
                "with different type, host, port, or user"
            )


def credential_groups(sources: Iterable[Source]) -> list[tuple[str, list[Source]]]:
    groups: dict[str, list[Source]] = {}
    for source in sources:
        groups.setdefault(source.credential_id, []).append(source)
    return list(groups.items())


def default_keychain_service(project_root: Path) -> str:
    slug = re.sub(r"[^A-Za-z0-9._-]+", "-", project_root.name).strip("-._")
    if not slug:
        digest = hashlib.sha256(str(project_root).encode("utf-8")).hexdigest()[:12]
        slug = f"project-{digest}"
    return f"codex.dbhub.{slug.lower()}"


def keychain_commands(service: str, credential_id: str) -> dict[str, str]:
    return {
        "check": shlex.join(
            [
                "/usr/bin/security",
                "find-generic-password",
                "-a",
                credential_id,
                "-s",
                service,
            ]
        ),
        "create_or_update": shlex.join(
            [
                "/usr/bin/security",
                "add-generic-password",
                "-U",
                "-a",
                credential_id,
                "-s",
                service,
                "-l",
                f"DBHub {credential_id}",
                "-w",
            ]
        ),
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate secure project-level DBHub multi-environment configuration."
    )
    parser.add_argument("--project-root", required=True, type=Path)
    parser.add_argument("--source", required=True, action="append", type=parse_source)
    parser.add_argument("--dbhub-version", required=True)
    parser.add_argument(
        "--npm-registry",
        help=(
            "Deprecated for setup: qualify releases with manage_dbhub_release.py "
            "and its --registry option instead."
        ),
    )
    parser.add_argument("--max-rows", type=int, default=1000)
    parser.add_argument("--connection-timeout", type=int, default=10)
    parser.add_argument("--query-timeout", type=int, default=30)
    parser.add_argument("--mysql-timezone", default=DEFAULT_MYSQL_TIMEZONE)
    parser.add_argument("--keychain-service")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--no-git-exclude", action="store_true")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    project_root = args.project_root.expanduser().resolve()
    if not project_root.is_dir():
        raise RuntimeError(f"project root is not a directory: {project_root}")
    if args.max_rows <= 0:
        raise RuntimeError("--max-rows must be positive")
    if args.connection_timeout <= 0 or args.query_timeout <= 0:
        raise RuntimeError("timeouts must be positive")
    if not DBHUB_VERSION_PATTERN.fullmatch(args.dbhub_version):
        raise RuntimeError(
            "--dbhub-version must be an exact stable semver such as '1.0.0'; "
            "tags, ranges, prereleases, URLs, and npm specs are not allowed"
        )
    if args.npm_registry is not None:
        raise RuntimeError(
            "--npm-registry is no longer a launcher option; use "
            "manage_dbhub_release.py check/qualify --registry instead"
        )
    if not MYSQL_TIMEZONE_PATTERN.fullmatch(args.mysql_timezone):
        raise RuntimeError(
            "--mysql-timezone must be 'local', 'Z', or an offset like '+08:00'"
        )

    sources: list[Source] = args.source
    ensure_unique_sources(sources)
    keychain_service = args.keychain_service or default_keychain_service(project_root)
    if not KEYCHAIN_SERVICE_PATTERN.fullmatch(keychain_service):
        raise RuntimeError(
            "--keychain-service must use only letters, digits, '.', '_' or '-'"
        )

    codex_config_path = project_root / ".codex" / "config.toml"
    dbhub_dir = project_root / ".codex" / "dbhub"
    dbhub_config_path = dbhub_dir / "dbhub.toml"
    launcher_path = dbhub_dir / "start-dbhub.zsh"

    existing_codex_config = (
        codex_config_path.read_text(encoding="utf-8")
        if codex_config_path.exists()
        else ""
    )
    generated_paths = (dbhub_config_path, launcher_path)
    replacement_required = any(path.exists() for path in generated_paths) or (
        MCP_HEADER in existing_codex_config
    )
    for generated_path in generated_paths:
        if generated_path.exists() and not args.force and not args.dry_run:
            raise RuntimeError(
                f"{generated_path} already exists; inspect it and rerun with --force"
            )

    codex_config = upsert_mcp_table(
        existing_codex_config,
        render_mcp_table(project_root),
        force=args.force or args.dry_run,
    )
    dbhub_config = render_dbhub_config(
        sources,
        max_rows=args.max_rows,
        connection_timeout=args.connection_timeout,
        query_timeout=args.query_timeout,
        mysql_timezone=args.mysql_timezone,
    )
    launcher = render_launcher(
        sources,
        dbhub_version=args.dbhub_version,
        keychain_service=keychain_service,
        config_sha256=hashlib.sha256(
            dbhub_config.encode("utf-8")
        ).hexdigest(),
    )

    summary = {
        "mode": "dry-run" if args.dry_run else "write",
        "project_root": str(project_root),
        "sources": [
            {
                "id": source.source_id,
                "label": source.label,
                "type": source.db_type,
                "endpoint": f"{source.host}:{source.port}/{source.database}",
                "user": source.user,
                "password_env": source.password_env,
                "keychain_account": source.credential_id,
            }
            for source in sources
        ],
        "keychain": {
            "service": keychain_service,
            "credentials": [
                {
                    "account": credential_id,
                    "sources": [
                        source.source_id for source in credential_sources
                    ],
                    **keychain_commands(keychain_service, credential_id),
                }
                for credential_id, credential_sources in credential_groups(sources)
            ],
        },
        "files": [
            str(codex_config_path),
            str(dbhub_config_path),
            str(launcher_path),
        ],
        "git_exclude": "skipped" if args.no_git_exclude else "project-local .codex/",
        "replacement_required": replacement_required,
        "dbhub_version": args.dbhub_version,
        "runtime_mode": "qualified",
    }

    if not args.dry_run:
        atomic_write(dbhub_config_path, dbhub_config, 0o600)
        atomic_write(launcher_path, launcher, 0o700)
        # Enable the MCP entry only after both files it references are durable.
        atomic_write(codex_config_path, codex_config, 0o600)
        if not args.no_git_exclude:
            summary["git_exclude_path"] = add_git_exclude(project_root)

    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (RuntimeError, OSError) as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(1)
